-- SALDO DE LAS CUENTAS

-- TRANSFERENCIAS QUE SE ACREDITAN
SELECT TRA_CUE_DESTINO, SUM(TRA_MONTO)
FROM gd_esquema.transferencias
WHERE TRA_FECHA <= GETDATE() -- ME ASEGURO QUE SE HAYA ACREDITADO
AND TRA_CUE_DESTINO IS NOT NULL AND TRA_CUE_DESTINO > 0
-- AND TRA_CUE_DESTINO = CUE_ID
GROUP BY TRA_CUE_DESTINO
UNION ALL
-- TRANSFERENCIAS QUE SE DEBITAN
SELECT TRA_CUE_ORIGEN, (- SUM(TRA_MONTO))
FROM gd_esquema.transferencias
WHERE TRA_FECHA <= GETDATE() -- ME ASEGURO QUE SE HAYA DEBITADO
AND TRA_CUE_ORIGEN IS NOT NULL AND TRA_CUE_ORIGEN > 0
-- AND TRA_CUE_ORIGEN = CUE_ID
GROUP BY TRA_CUE_ORIGEN
UNION ALL
-- CHEQUES QUE SE ACREDITAN
SELECT CHE_CUE_DESTINO, SUM(CHE_MONTO)
FROM gd_esquema.cheques
WHERE CHE_FECHA <= GETDATE() -- ME ASEGURO QUE SE HAYA ACREDITADO
AND CHE_CUE_DESTINO IS NOT NULL AND CHE_CUE_DESTINO > 0
-- AND TRA_CUE_DESTINO = CUE_ID
GROUP BY CHE_CUE_DESTINO
UNION ALL
-- CHEQUES QUE SE DEBITAN
SELECT CHE_CUE_ORIGEN, (- SUM(CHE_MONTO))
FROM gd_esquema.cheques
WHERE CHE_FECHA <= GETDATE() -- ME ASEGURO QUE SE HAYA ACREDITADO
AND CHE_CUE_ORIGEN IS NOT NULL AND CHE_CUE_ORIGEN > 0
-- AND CHE_CUE_ORIGEN = CUE_ID
GROUP BY CHE_CUE_ORIGEN


-- PLAZOS FIJOS
